version: '3.7'

x-defaults: &defaults
  restart: always
  build: .
  depends_on:
    - redis
    - postgres
    - memcached
  env_file:
    - ./.env
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    SENTRY_SINGLE_ORGANIZATION: 0
  volumes:
    - sentry-data:/var/lib/sentry/files


services:
  memcached:
    restart: always
    image: memcached:1-alpine

  redis:
    restart: always
    image: redis:5-alpine

  postgres:
    restart: always
    image: postgres:11-alpine
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults
    ports:
      - 9000:9000

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker


volumes:
    sentry-data:
      external: true
    sentry-postgres:
      external: true
